### PR TITLE
Fix scoped plugin dependencies

### PR DESCRIPTION
**Pull request by rgov**
Plugins declared dependencies on packages in the @hapi scope, but dependency resolution works only with the unscoped package name.

I'm curious if it works on your system as-is. I'm trying to debug it further down the stack:

* https://stackoverflow.com/questions/61084503
* https://github.com/hapijs/hapi/issues/4088

### CODE REVIEW

**Comment by webbpinner** [comment]
what version of node.js is the docker package installing?  v8.x??  This might be a v8.x vs v12 issue... I was working on updating the code to work with v12 since v8.x is no longer supported and I may have accidentally updated the v8.x branch (master)

**Comment by rgov** [comment]
The Docker container uses node  12.9.1 (and will automatically use the latest release from the 12.x branch whenever it is rebuilt).

**Comment by rgov** [comment]
Related commit: 3d6a2e2

**Comment by webbpinner** [comment]
ok... I think I found the issue.  It wasn't nodeJS it was hapi.  The latest version of hapi (v19.x) requires the @hapi scope AND nodeJS v12.x.  These changes were applied to the master branch by mistake.  I've reverted those changes and will now merge the pull request.  Thank you for helping diagnose the issue.

**Pull request merged**
